project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <description>User&apos;s bid on listing (Product)</description>
    <label>Bid</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project2/force-app/main/default/objects/Bid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The offered price for the listing (product)</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

project2/force-app/main/default/objects/Bid__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/objects/Product2/fields/Current_Highest_Bid__c.field-meta.xml
<CustomField>
    <fullName>Current_Highest_Bid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Highest Bid</label>
    <referenceTo>Bid__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Product_Highest_Bid</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/classes/BidTrigger_Helper.cls
public with sharing class BidTrigger_Helper {
  // Display error messages if required field is null
  public static void requiredFields(List<Bid__c> bids){
    for (Bid__c bid : bids) {
      if (bid.Product__c == null) {
        bid.Product__c.addError('Product is required');
      }
      if (bid.Price__c == null) {
        bid.Price__c.addError('Price is required');
      }
    }
  }
  // Update highest current bid on listing
  public static void updateCurrentHighestBid(List<Bid__c> bids){
    for (Bid__c bid : bids) {
      try {
        // Query for listing associated with bid
        Product2 listing = [
          SELECT Id, Current_Highest_Bid__c
          FROM Product2 
          WHERE Id =: bid.Product__c
          LIMIT 1
        ];
        // Check if bid is greater than current highest bid on listing
        if (bid.Price__c > listing.Current_Highest_Bid__c || listing.Current_Highest_Bid__c == null) {
          // Update current highest bid
          listing.Current_Highest_Bid__c = bid.Price__c;
          update listing;
        }
      } catch (Exception e) {
        System.debug('An unexpected error has occurred: ' + e.getMessage());
      }
    }
  }
}