project2/force-app/main/default/objects/Bid__c/Bid__c.object-meta.xml
<CustomObject>
    <description>User&apos;s bid on listing (Product)</description>
    <label>Bid</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Bid ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project2/force-app/main/default/objects/Bid__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>The offered price for the listing (product)</description>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

project2/force-app/main/default/objects/Bid__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bids</relationshipLabel>
    <relationshipName>Bids</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/objects/Product2/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>The date and time the bidding ends</description>
    <label>Close Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

project2/force-app/main/default/objects/Product2/fields/Minimum_Price__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Price__c</fullName>
    <label>Minimum Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

project2/force-app/main/default/classes/BidTrigger_Helper_Test.cls
@isTest
public with sharing class BidTrigger_Helper_Test {
  @TestSetup
  static void makeTestData() {
    Product2 p = new Product2(Name='Test Product', Close_Date__c=datetime.newInstance(2022, 2, 2, 7, 0, 0), Minimum_Price__c=100);
    insert p;
  }
  
  /*@isTest
  public static void productNegativeTestCase() {
    // Start Test
    Test.startTest();
    // Query 
    Product2 p = [SELECT Id, Name
                FROM Product2
                WHERE name='Test Product' LIMIT 1];
    // New Bid
    Bid__c item = new Bid__c(Price__c=p.id);
    // Insert
    Database.saveResult sr = Database.insert(item, false);
    // Check if test passed
    System.assert(!sr.isSuccess());
    // Stop Test
    Test.stopTest();
  } 
  
  @isTest
  public static void priceNegativeTestCase() {
    // Start Test
    Test.startTest();
    // Query 
    Product2 p = [SELECT Id, Name
                FROM Product2
                WHERE name='Test Product' LIMIT 1];
    // New Bid
    Bid__c item = new Bid__c(Product__c=p.id);
    // Insert
    Database.saveResult sr = Database.insert(item, false);
    // Check if test passed
    System.assert(!sr.isSuccess());
    // Stop Test
    Test.stopTest();
  }*/
}