project2/force-app/main/default/objects/Product2/fields/Chatter_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_ID__c</fullName>
    <label>Chatter Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

project2/force-app/main/default/objects/Product2/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>The date and time the bidding ends</description>
    <label>Close Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

project2/force-app/main/default/objects/Product2/fields/Current_Highest_Bid__c.field-meta.xml
<CustomField>
    <fullName>Current_Highest_Bid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Highest Bid</label>
    <referenceTo>Bid__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Product_Highest_Bid</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/objects/Product2/fields/Seller__c.field-meta.xml
<CustomField>
    <fullName>Seller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Seller</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

project2/force-app/main/default/classes/ProductTrigger_Helper.cls
public without sharing class ProductTrigger_Helper {
    public ProductTrigger_Helper() {

    }



    public static void createAssociatedChatterGroup(Product2 listing) {

        CollaborationGroup chatterGroup = new CollaborationGroup();
            chatterGroup.CollaborationType = 'Private';
            chatterGroup.Description = 'Chatter Group for Item ' + listing.Name;
            chatterGroup.Name = listing.Name + ': ' + listing.Seller__c.Name;
            chatterGroup.isAutoArchiveDisabled = true;
        insert chatterGroup;

        listing.Chatter_Group_Id__c = chatterGroup.id;
        update listing;

        CollaborationGroupRecord associatedItem = new CollaborationGroupRecord();
            associatedItem.RecordId = listing.id;
            associatedItem.CollaborationGroupId = chatterGroup.id;
        insert associatedItem;

        CollaborationGroupMember sellerMember = new CollaborationGroupMember();
            sellerMember.MemberId = listing.Seller__c.id;
            sellerMember.CollaborationGroupId = chatterGroup.id;
        insert sellerMember;
    }

    public static void newHighestBidMessage(Product2 oldListing, Product2 newListing) {
        if(newListing.Current_Highest_Bid__c.Price__c > oldListing.Current_Highest_Bid__c.Price__c) {

            String message = 'A new highest bid has been posted for ' + newListing.Name + 
                                    ': ' + newListing.Current_Highest_Bid__c.Bidder__c.Price__c + ' by {' + newListing.Current_Highest_Bid__c.Bidder__c.id +
                                    '}, beating ' + oldListing.Current_Highest_Bid__c.Bidder__c.Price__c + ' by {' + oldListing.Current_Highest_Bid__c.Bidder__c.id + '}.';

            ConnectApi.FeedItem fi = (ConnectApi.FeedItem) ConnectApiHelper.postFeedItemWithMentions(Network.getNetworkId(), newListing.Chatter_Group_Id__c, message);

        }
    }

    public static void sendClosingMessage(Product2 listing) {
            if((listing.IsActive == false) && (System.now() > listing.Close_Date__c)) {

                String message = 'The bidding period for this item has now closed. Thank you to all participants.' +
                                        'The winner of the auction is: {' + listing.Current_Highest_Bid__c.Bidder__c.id + '} with amount ' +
                                        listing.Current_Highest_Bid__c.Price__c + '. The seller will contact you soon.';

                ConnectApi.FeedItem fi = (ConnectApi.FeedItem) ConnectApiHelper.postFeedItemWithMentions(Network.getNetworkId(), listing.Chatter_Group_Id__c, message);
            }
        }




    /* Due to governor limits (100 max schedulable Apex actions at a time), this will have to be implemented
        in Process Builder (which has a limit of 1000 per hour) instead, but we can call the process from this trigger at least
    public void handleCloseDate(Product listing) {


    } */
}